<a href="https://colab.research.google.com/github/kKravtsova/data_and_python/blob/main/Data_Investigation_Project_kkravtsova.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Data investigation project
---

Use what you have learnt so far about reading data files and displaying rows, columns, unique values, etc, to investigate and produce some printed information from this data set: https://raw.githubusercontent.com/futureCodersSE/working-with-data/main/Data%20sets/housing_in_london_yearly_variables.csv

In [2]:
# uploading dataset as dataframe and checking data in it via presenting first 10 records
import pandas as pd

url = "https://raw.githubusercontent.com/futureCodersSE/working-with-data/main/Data%20sets/housing_in_london_yearly_variables.csv"
df = pd.read_csv(url)
df.head(10)

,code,area,date,median_salary,life_satisfaction,mean_salary,recycling_pct,population_size,number_of_jobs,area_size,no_of_houses,borough_flag
0,E09000001,city of london,1999-12-01,33020.0,NaN,48922,0,6581.0,NaN,NaN,NaN,1
1,E09000002,barking and dagenham,1999-12-01,21480.0,NaN,23620,3,162444.0,NaN,NaN,NaN,1
2,E09000003,barnet,1999-12-01,19568.0,NaN,23128,8,313469.0,NaN,NaN,NaN,1
3,E09000004,bexley,1999-12-01,18621.0,NaN,21386,18,217458.0,NaN,NaN,NaN,1
4,E09000005,brent,1999-12-01,18532.0,NaN,20911,6,260317.0,NaN,NaN,NaN,1
5,E09000006,bromley,1999-12-01,16720.0,NaN,21293,13,294902.0,NaN,NaN,NaN,1
6,E09000007,camden,1999-12-01,23677.0,NaN,30249,13,190003.0,NaN,NaN,NaN,1
7,E09000008,croydon,1999-12-01,19563.0,NaN,22205,13,332066.0,NaN,NaN,NaN,1
8,E09000009,ealing,1999-12-01,20580.0,NaN,25046,12,302252.0,NaN,NaN,NaN,1
9,E09000010,enfield,1999-12-01,19289.0,NaN,21006,9,272731.0,NaN,NaN,NaN,1

In [5]:
# defining unique areas
unique_area = df["area"].unique().tolist()
unique_area

['city of london',
 'barking and dagenham',
 'barnet',
 'bexley',
 'brent',
 'bromley',
 'camden',
 'croydon',
 'ealing',
 'enfield',
 'greenwich',
 'hackney',
 'hammersmith and fulham',
 'haringey',
 'harrow',
 'havering',
 'hillingdon',
 'hounslow',
 'islington',
 'kensington and chelsea',
 'kingston upon thames',
 'lambeth',
 'lewisham',
 'merton',
 'newham',
 'redbridge',
 'richmond upon thames',
 'southwark',
 'sutton',
 'tower hamlets',
 'waltham forest',
 'wandsworth',
 'westminster',
 'north east',
 'north west',
 'yorkshire and the humber',
 'east midlands',
 'west midlands',
 'east',
 'london',
 'south east',
 'south west',
 'inner london',
 'outer london',
 'england',
 'united kingdom',
 'great britain',
 'england and wales',
 'northern ireland',
 'scotland',
 'wales']

In [7]:
#selecting area, median_salary, mean_salary series
df[["area", "median_salary", "mean_salary"]].tail(100)

                   area  median_salary mean_salary
971              barnet        29927.0       36776
972              bexley            NaN       34496
973               brent        30366.0       35830
974             bromley        30762.0       35201
975              camden        39198.0       46502
...                 ...            ...         ...
1066      great britain        30446.0       37603
1067  england and wales        30500.0       37865
1068   northern ireland        27434.0       32083
1069           scotland        30000.0       34916
1070              wales        27500.0       31251

[100 rows x 3 columns]

In [13]:
# seleting data about area and population, displaying some rows
df.loc[300:400, ["area", "population_size", "area_size"]]

                  area  population_size  area_size
300     united kingdom       59950364.0        NaN
301      great britain       58236322.0        NaN
302  england and wales       53152022.0        NaN
303   northern ireland        1714042.0        NaN
304           scotland        5084300.0        NaN
..                 ...              ...        ...
396             london        7597825.0   159471.0
397         south east        8270861.0        NaN
398         south west        5119840.0        NaN
399       inner london        2989670.0    32796.0
400       outer london        4608155.0   126676.0

[101 rows x 3 columns]